### ISSUE TITLE
New feature: Max Resubmit Count

### ISSUE THREAD

**Issue by verolero86** [olcf/olcf-test-harness#10]
From @MichaelBrim The only reason I can think of to keep the resubmit key in the test input file would be for cases where the test should never resubmit (e.g., a functionality test that should only run once). However, I think that capability maps better to a max_resubmit key that is more general, and would allow tests to limit the total number of times they get run. Applications that don't need a limit would not need to have the key in their input file.

This could be monitored from the monitor but harness changes would still be needed:
>From @MichaelBrim: adding it to where the status of the job is updated could be an option but would require more code changes.

**Comment by ddietz89** [comment]
Proposed solution to this in #12
