### ISSUE TITLE
LogLevel flags hard-coded in several object classes

### ISSUE THREAD

**Issue by hagertnl** [olcf/olcf-test-harness#102]
There are several classes that have hard-coded loglevel/threshold levels. For example, in `harness/libraries/regresstion_test.py`:
```
                logger_threshold = self.__log_level
                fh_threshold_log_level = "INFO"
                ch_threshold_log_level = "CRITICAL"
                a_logger = rgt_logger_factory.create_rgt_logger(logger_name=logger_name,
                                      fh_filepath=fh_filepath,
                                      logger_threshold_log_level=logger_threshold,
                                      fh_threshold_log_level=fh_threshold_log_level,
                                      ch_threshold_log_level=ch_threshold_log_level)
```
The logger threshold is inherited, which is good, but the file handler & console handler log levels are hardcoded.

**Comment by hagertnl** [comment]
I believe the desired behavior here would be to have all `fh_threshold_log_level` and `ch_threshold_log_level` just inherit from `self.__log_level`, which is what is provided by `--loglevel` to `runtests.py`.

**Comment by hagertnl** [comment]
This likely is contributing to #37  as well. The log message shows in the Log file, but not the console.

**Comment by hagertnl** [comment]
This also contributes to #53

**Comment by ddietz89** [comment]
Just needs a review of log level appropriateness in #114
