### ISSUE TITLE
Symlinks are not getting copied but getting resolved

### ISSUE THREAD

**Issue by verolero86** [olcf/olcf-test-harness#11]
Update should go here: 
https://github.com/olcf/olcf-test-harness/blob/345d5ec9ef37c90e667ac6acd1cc62a76270db93/harness/machine_types/base_machine.py#L442

**Comment by verolero86** [comment]
When `Source` has symlinks in it, the copy step crashes.

**Comment by verolero86** [comment]
Resulting copy should look exactly like original, good symlinks and bad symlinks included.

**Comment by hagertnl** [comment]
Added argument `symlinks=True` to copytree command (there is only one copytree command, so only one source line changed). Tested on Spock, works.

**Comment by hagertnl** [comment]
Fixed in PR #20
