### ISSUE TITLE
Update status to include launchID and resubmission count

### ISSUE THREAD

**Issue by verolero86** [olcf/olcf-test-harness#16]
This could be a helpful feature to figure out how many resubmission of each launch happened or when a chain of resubmissions breaks due to system failures.

**Comment by verolero86** [comment]
Mike B: w.i.p nearly ready

**Comment by MichaelBrim** [comment]
It's ready for review. I'd welcome feedback on format for the "launch id". Currently, it's a timestamp, but I also thought including the `$USER` who initiated the launch might be useful.

**Comment by verolero86** [comment]
Resolved by #22
