### ISSUE TITLE
Allow option to merge build's stdout and stderr

### ISSUE THREAD

**Issue by verolero86** [olcf/olcf-test-harness#2]
Currently, by default, the OTH will save stdout and stderr for the build step in separate files. A single file can be useful to troubleshoot build issues. We should consider making this an option or change the default behavior.

**Comment by verolero86** [comment]
Can we have both options all the time? stderr + stdout, stdouterr.

**Comment by hagertnl** [comment]
Currently, the code uses Python's subprocess.Popen method for printing separately to stdout and stderr. Preference of alternatives:
1. see if it is possible with subprocess.Popen options to print to stdout, stderr, stdout+stderr
2. is there another subprocess function that may work
3. is there another python module that may work
4. change the build command (append redirection operators to the build command)
5. maybe combined and split outputs is not the way to go

**Comment by hagertnl** [comment]
subprocess.Popen has been superceded by subprocess.run (run implicitly uses Popen, just a level of abstraction for devs). You can print separately or join stderr to stdout, but not both. Documentation: https://docs.python.org/3/library/subprocess.html#subprocess.run. It is also possible to spawn a background thread to continually monitor stdout and stderr, and capture/redirect as necessary: https://codereview.stackexchange.com/questions/6567/redirecting-subprocesses-output-stdout-and-stderr-to-the-logging-module. This would be prone to issues with buffers and with interlacing the stderr and stdout.

The subprocess module does not appear to be well-suited for this.

**Comment by hagertnl** [comment]
os.system is one of the only other methods to spawn a shell process from within Python. It is less powerful than subprocess, in terms of built-in redirection. Python solutions to this are generally convoluted and suffer from inconsistent interlacing of the stderr and stdout streams.

A safer solution appears to be scanning the build command for built-in redirection, '>', '2>', '&>' (if the command already redirects stdout to a file, there's no need to add another redirection). If there is no redirection, append '| tee stdout.txt 2| tee stderr.txt &> stdout_stderr.txt'. This could be implemented as a simple function that executes right before an existing Popen call to modify the command string.

**Comment by verolero86** [comment]
Default: combined 
Option: split

**Comment by verolero86** [comment]
Fixed in [PR#13](https://github.com/olcf/olcf-test-harness/pull/13)
