### ISSUE TITLE
Replacements variable `project_id` is overriding RGT_ACCT_ID 

### ISSUE THREAD

**Issue by verolero86** [olcf/olcf-test-harness#24]

**Comment by hagertnl** [comment]
When an alternative project ID is provided via RGT_ACCT_ID, it's overridden by the replacement variable `project_id` in each test.

If project_id = stf016 and RGT_ACCT_ID=stf017, stf017 should override the test-set stf016;
expected behavior:
sbatch -Astf017 run_test.sh
observed behavior:
sbatch -Astf016 run_test.sh

**Comment by hagertnl** [comment]
This same behavior happens for RGT_SUBMIT_QUEUE, and is caused by `Override=True` while reading the rgt input file. Testing setting override to False.

**Comment by MichaelBrim** [comment]
I may be in the minority, but my opinion is that if project_id is set in the test, it should be there for a specific reason (i.e., the test will ONLY run correctly for that project id). In that case, we don't want to override it. For the majority of tests that exist today, project_id is only there for historical reasons, and we should work to remove it and others (e.g., batch_queue) that are basically just setting the default value.

**Comment by hagertnl** [comment]
That is a good point, that the test project ID is likely set for a reason.

I think the environment variable should still be the highest priority, for the use case that a project ID might need to be changed by different users, and they wouldn't want to modify each test config file in order to submit to their allowable project IDs.

**Comment by verolero86** [comment]
After discussing, the consensus is that environment variables set manually at launch time will be the highest priority (i.e., `RGT_SUBMIT_QUEUE`,`RGT_ACCT_ID`).

**Comment by MichaelBrim** [comment]
Ok, I have verified that we are using the environment variables (`RGT_SUBMIT_QUEUE`, `RGT_PROJECT_ID`|`RGT_ACCT_ID`) to update the job submission commands (see harness/machine_types/lsf.py for example). Unfortunately, I also found that if both `RGT_PROJECT_ID` and `RGT_ACCT_ID` are set, the former has precedence. This means that Nick's fix isn't quite complete for tests where `project_id` is set in the `rgt_test_input.ini`. My suggestion would be to deprecate the use of RGT_ACCT_ID in favor of RGT_PROJECT_ID.

**Comment by hagertnl** [comment]
Along these same lines, is it intended for `batch_queue` or `submit_queue` replacement to provide a test-specific partition to run in? I created a unit test that sets bad values for `batch_queue` and `project_id`, and the batch_queue value is not being used. `sbatch -p batch` is seen in the submit command. The `RGT_SUBMIT_QUEUE` variable does override whatever is getting set. I also tried changing `batch_queue` to `submit_queue` to match with the environment variable, and this didn't change the issue.

I am also in favor of deprecating use of RGT_ACCT_ID in favor of RGT_PROJECT_ID.

**Comment by hagertnl** [comment]
After some discussion, I realized that there was likely an intent to RGT_ACCT_ID.

The <machine>.ini file adds a default RGT_PROJECT_ID to the environment, if one is not already present. The current way the harness operates is to then override that if there is a `project_id` in the test's replacements section. However, the harness has no way of knowing if the currently set RGT_PROJECT_ID came from machine.ini or from the user, so it's overridden.

But that makes me think that the purpose of RGT_ACCT_ID is to provide input that is intended to only come from the user -- so the *intended* priority (in order of lowest to highest) is:

1. <machine>.ini project_id (lowest)
2. rgt_test_input.ini project_id
3. RGT_ACCT_ID (highest)

That's not currently how things work, but I would propose that we deprecate the use of `RGT_PROJECT_ID` on the command-line in favor of `RGT_ACCT_ID`. That way, if `RGT_ACCT_ID` is set, it will override whatever is in the machine.ini AND rgt_test_input.ini. This would appear to be synonymous with how RGT_SUBMIT_QUEUE and batch_queue are used.

**Comment by hagertnl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix RGT_ACCT_ID, RGT_BATCH_QUEUE in harness](https://trello.com/c/4IDcsk8Z/25-fix-rgtacctid-rgtbatchqueue-in-harness)
