### ISSUE TITLE
batch_queue option in ini files does not control queue submitted to

### ISSUE THREAD

**Issue by tom-papatheodore** [olcf/olcf-test-harness#5]
If I add a `batch_queue` variable in a test's .ini file and then use that variable in the slurm template (i.e., `#SBATCH __batch_queue__`), it gets picked up in the slurm script that is created, but it doesn't actually change the queue that the job gets submitted to. 

For example, if I use `batch_queue=mi100` on Spock (which doesn't exist), I do see `#SBATCH mi100` in my slurm script that gets created from the template, but I still submit to the batch queue.

Is there an environment variable that is set to `batch` by default somewhere?

**Comment by MichaelBrim** [comment]
@tom-papatheodore  I assume it's just a typo in your message that you have `#SBATCH mi100` rather than `#SBATCH -p mi100`?

**Comment by tom-papatheodore** [comment]
@MichaelBrim Yes, that was a typo. The template actually reads `#SBATCH -p __batch_queue__` and the actual script that gets generated from the template reads `#SBATCH -p mi100`

**Comment by verolero86** [comment]
one way to override is `$RGT_SUBMIT_QUEUE`.
