### ISSUE TITLE
resubmissions do not update RGT_* environment variables

### ISSUE THREAD

**Issue by hagertnl** [olcf/olcf-test-harness#72]
When resubmit is set to 1 and the `--mode stop` is not specified, jobs resubmit automatically. Demonstration of problem:

1) First test submitted is 1665756354.1568162, submitted with `--mode start`
2) Test ID 1665757503.2127497 is launched by the resubmit of the first job
3) In the second (and every test after) test's job.environ:
```
RGT_TEST_RUNARCHIVE_DIR=/.../Run_Archive/1665756354.1568162
```
I frequently use RGT_TEST_RUNARCHIVE_DIR in check scripts to provide a mechanism for absolute paths (although, alternatives certainly exist). Should this environment variable be carried over into the new test, or remain assigned to the first test?

**Comment by verolero86** [comment]
Thanks for finding that @hagertnl ! this definitely seems like a bug to me.

**Comment by hagertnl** [comment]
I've isolated the issue to https://github.com/olcf/olcf-test-harness/blob/f57f553db39a8dde8e700e7968a9acc14bfe3573/harness/bin/test_harness_driver.py#L450 . This call to `set_harness_environment` will need to override the current environment variables. Incorrect output:
```
Generated launch id: frontier_test/hagertnl@2022-10-20T14:41:59.82
Generated test unique id: 1666291319.8275685
<line 450 call to set_harness_environment here>
RGT_APP_SOURCE_DIR is already set. Skipping.
RGT_TEST_SCRIPTS_DIR is already set. Skipping.
RGT_TEST_BUILD_DIR is already set. Skipping.
RGT_TEST_WORK_DIR is already set. Skipping.
RGT_TEST_STATUS_DIR is already set. Skipping.
RGT_TEST_RUNARCHIVE_DIR is already set. Skipping.
```
As is shown by this, all the build, work, status, and runarchive dirs are not set, since they already exist. Fortunately, this section of code only adds these variables to the environment, so it should be safe to set the override=True flag for this call without any side effects.
