### ISSUE TITLE
Validate or support ~ or env vars in Path_to_tests (and other inputs)

### ISSUE THREAD

**Issue by ddietz89** [olcf/olcf-test-harness#93]
Having a path such as:

Path_to_tests = ~/tmp/tests/

"Sort of" works, but then crashes after the first submission with unhelpful errors:

```
Submitting job from SLURM class using batchfilename job.slurm
sbatch  -p batch  -A stf016 job.slurm
SLURM jobID =  292334
build exit value = 0
submit exit value = 0
Application minisweep future exception:
[Errno 2] No such file or directory: '~/tmp/tests//minisweep/hip_n0001/Scripts/.kill_test'
```

I propose either fully supporting ~ and environment variables in Path_to_tests, or at least validating the path so that it does not crash with confusing error messages halfway through.

Validation or resolution could possibly be done here:

https://github.com/olcf/olcf-test-harness/blob/cc5e57f428e3389b6fb6952767c79c5afab05c32/harness/libraries/input_files.py#L105

**Comment by hagertnl** [comment]
If we support environment variables in `Path_to_tests`, then I think we also need to support environment variables in `RGT_PATH_TO_SSPACE`.
